/*
*Name: Daniel Yu
Due Date: April 4, 2025
 */

import java.awt.event.ActionEvent;      // event management
import java.awt.event.ActionListener;   // action listeners
import javax.swing.Timer;               // timer module
import java.awt.Graphics;               // graphics library
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;         // for when you press keys on keyboard
import java.awt.AWTEvent;
import java.awt.*;                      // imports the java graphics

public class MainDrawingArea extends javax.swing.JPanel {

    Timer t1;
    boolean isJumping;
    int curKey; // the current key being pressed

    public MainDrawingArea() {
        this.isJumping = false;
        GameManager.setup();

        //Initialize the components
        initComponents();
        //Allowsm the main panel be focused so the user can press the keys
        setFocusable(true);
        //Includes a key listener
        addKeyListener(new MainDrawingArea.AL());
        //Makes the delay
        t1 = new Timer(20, new MainDrawingArea.TimerListener());
        //Begins the timer
        t1.start();
        //Enables mouse events so you can refocus on the panel so you can control the game
        this.enableEvents(AWTEvent.MOUSE_EVENT_MASK | AWTEvent.MOUSE_MOTION_EVENT_MASK
                | AWTEvent.KEY_EVENT_MASK | AWTEvent.FOCUS_EVENT_MASK
                | AWTEvent.COMPONENT_EVENT_MASK | AWTEvent.WINDOW_EVENT_MASK);
    }

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);

        GameObject[] objects = GameManager.getGameObjects();
        
        //Drawing the images for all game objects
        for (int i = 0; i < objects.length; i++) {
            GameObject obj = objects[i];
            g.drawImage(obj.getImage(), (int) obj.getX(), (int) obj.getY(), obj.getWidth(), obj.getHeight(), this);
        }
        
        //Logic for game running
        if (Player.getLives() > 0) {
            //Update the logic in the game manager class
            GameManager.update();
            //Diplay the points and lives
            g.setColor(Color.BLACK);
            g.drawString("Points: " + GameManager.getPoints(), 20, 20);
            g.drawString("Lives: " + Player.getLives(), 20, 40);

        }
        
        //if the lives are at most 0, then it is game over
        else if (Player.getLives() <= 0) {
            g.drawString("GAME OVER: Press R to Restart", 450, 300);
            GameManager.gameOver();
        }
        
        //Display the points and lives
        g.setColor(Color.BLACK);
        g.drawString("Points: " + GameManager.getPoints(), 20, 20);
        g.drawString("Lives: " + Player.getLives(), 20, 40);
    }

    private class TimerListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent ae) {
            repaint();                                      // repaints the screen
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public class AL extends KeyAdapter {

        @Override
        public void keyPressed(KeyEvent e) {
            // get the key pressed event - key that was pressed
            curKey = e.getKeyCode();
            if (curKey == KeyEvent.VK_SPACE) {
                if (!isJumping && Player.getLives() > 0) {
                    Player player = (Player) GameManager.getGameObjects()[6];
                    player.jump();
                }
            }
            if (curKey == KeyEvent.VK_R) {
                if (Player.getLives() <= 0) {
                    GameManager.restartGame();
                    GameManager.update();
                }
            }
        }

        @Override
        public void keyReleased(KeyEvent e) {
            curKey = e.getKeyCode();
            if (curKey == KeyEvent.VK_SPACE) {
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
